---
title: "chapter6.Rmd"
output: html_document
---

```{r}
RATS <- read.table("https://raw.githubusercontent.com/KimmoVehkalahti/MABS/master/Examples/data/rats.txt", sep = "\t", header = T)

BPRS <- read.table("https://raw.githubusercontent.com/KimmoVehkalahti/MABS/master/Examples/data/BPRS.txt", sep  =" ", header = T)

BPRSL<- BPRS %>% pivot_longer(cols = starts_with("week"), names_to = "Time")
BPRSL <- BPRSL %>% mutate(week = as.integer(substr(Time,5,5)))

RATSL <- RATS %>%
  gather(key = WD, value = Weight, -ID, -Group) %>%
  mutate(Time = as.integer(substr(WD,3,4))) 


library(tidyverse)
library(dplyr)
RATS$Group <- as.factor(RATS$Group)
RATS$ID <- as.factor(RATS$ID)
BPRS$treatment<- as.factor(BPRS$treatment)
BPRS$subject <- as.factor(BPRS$subject)
str(RATS)
colnames(RATS)
colnames(BPRS)
BPRS$bprs
str(BPRS)


```
```{r}
library(tidyverse)
library(dplyr)


ggplot(RATSL, aes(x = Time, y = Weight, group = ID)) +
  geom_line(aes(linetype = Group)) +
  scale_x_continuous(name = "Time (days)", breaks = seq(0, 60, 10)) +
  scale_y_continuous(name = "Weight (grams)") +
  theme(legend.position = "top")

library(ggplot2)

ggplot(BPRSL, aes(x = week, y = bprs, linetype = subject)) +
  geom_line() +
  scale_linetype_manual(values = rep(1:10, times=4)) +
  facet_grid(. ~ treatment, labeller = label_both) +
  theme(legend.position = "none") + 
  scale_y_continuous(limits = c(min(BPRSL$bprs), max(BPRSL$bprs)))
```

